# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
    datasource:
        name: prodtest
        url: jdbc:mysql://42.51.4.198:3336/prodtest
        username: root
        password: root
  
logging:
   level:
      ROOT: WARN
   file: springbootappdemo.log
